-- Additive and backward compatible: the previous deploy keeps working against this schema.

-- Audit trail: who acted, and a stable order for events written in one transaction.
ALTER TABLE public.audit_events ADD COLUMN IF NOT EXISTS actor_user_id uuid REFERENCES public.users(id);
ALTER TABLE public.audit_events ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE INDEX IF NOT EXISTS audit_events_project_seq_idx ON public.audit_events(project_id, seq DESC);

-- Exports: more formats, which figure, and at what resolution.
ALTER TABLE public.export_records DROP CONSTRAINT IF EXISTS export_records_format_check;
ALTER TABLE public.export_records ADD CONSTRAINT export_records_format_check
  CHECK (format IN ('png', 'tiff', 'pdf', 'svg'));
ALTER TABLE public.export_records ADD COLUMN IF NOT EXISTS artboard_id text;
ALTER TABLE public.export_records ADD COLUMN IF NOT EXISTS dpi integer
  CHECK (dpi IS NULL OR dpi BETWEEN 1 AND 2400);
CREATE INDEX IF NOT EXISTS export_records_project_created_idx
  ON public.export_records(project_id, created_at DESC);

-- Deleted projects become tombstones so their audit trail and export records survive.
ALTER TABLE public.projects DROP CONSTRAINT IF EXISTS projects_status_check;
ALTER TABLE public.projects ADD CONSTRAINT projects_status_check
  CHECK (status IN ('active', 'deleting', 'deleted'));
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

-- Version history reads, newest first.
CREATE INDEX IF NOT EXISTS project_versions_project_revision_idx
  ON public.project_versions(project_id, revision DESC);
